apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: job-runner
  namespace: monitoring
  labels:
    release: monitoring
    app: job-runner
spec:
  selector:
    matchLabels:
      app: job-runner
  namespaceSelector:
    matchNames: ["app"]
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
